name: ds-base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - pytorch
  - statsmodels
  - scipy
  - joblib
  - pip
  - smart-open
  - pip:
    - ruff
    - pre-commit
