# currently disabled; update on Github repo Actions
# verify all below
# following from perplexity

# name: ci

# on: [push, pull_request]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install ruff
#       - name: Run Ruff
#         run: ruff check .

#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up conda
#         uses: conda-incubator/setup-miniconda@v3
#         with:
#           activate-environment: ds-base
#           environment-file: environments/base.yml
#           auto-activate-base: false
#       - name: Run tests
#         shell: bash -l {0}
#         run: |
#           conda info
#           conda list
#           # Add your test commands here
